### ISSUE TITLE
how do i make a multiboard image board

### ISSUE THREAD

**Issue by get52** [tslocum/TinyIB#18]
pls

**Comment by tslocum** [comment]
While TinyIB is designed as a single board script, it can share bans between boards if you use MySQL.  You'll need to create copies of TinyIB and configure them separately.

**Comment by Wqer555** [comment]
You can use symlinks between source files, except the settings file. It's hackish but it works. And it's a good way of synchronising changes between boards. The bans DB is easy to share, but you should make a separate one for posts. TinyIB can likely be forked to hold board names in the DB and generate pages accordingly. But it would take some work.
