### ISSUE TITLE
how2 make a le css changer

### ISSUE THREAD

**Issue by get52** [tslocum/TinyIB#20]
u know like u get drop down list and it shows ur le themes

pls le help
thanks le friends

**Comment by Wqer555** [comment]
First you import this: https://gist.github.com/Wqer555/847184d60f50546fee4a
Using 
        <script src="/js/css.js" type="text/javascript"></script>
Then you make your styles like this:
        <link rel="stylesheet" type="text/css" href="css/night.css" title="Night">
        <link rel="stylesheet" type="text/css" href="css/green.css" title="Green">
And finally you make your link:
<a href="#" onclick="setActiveStyleSheet('Night'); return false;">Night</a>
<a href="#" onclick="setActiveStyleSheet('Green'); return false;">Green</a>

**Comment by get52** [comment]
In what html file do I put the <link> tabs?

Also thanks for helping me even after all the stupid "le"'s I put in there. haha

**Comment by Wqer555** [comment]
I'm not sure what you mean by "tabs" but you would probably work with the inc/html.php file. It's what generates the HTML for the page each time you rebuild the board. The Javascript is its own file. The script and link tags go into head tag. The anchor tags go anywhere in the body tag.

**Comment by get52** [comment]
Thank you very much sir!

life saver
<3
