### ISSUE TITLE
Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by Justawinterwolf2012** [tslocum/TinyIB#23]
Some of the constructors used in TinyIB have been depreciated in PHP 7.0.0, and is preventing me from smoothly using it.
![untitled](https://cloud.githubusercontent.com/assets/16302135/16361214/2620eff0-3b3d-11e6-810f-f4f002e55892.png)

**Comment by Wqer555** [comment]
https://secure.php.net/manual/en/language.oop5.decon.php

The code should be refactored to use **__construct()**.

**Comment by tslocum** [comment]
Thanks for the report and follow-up.
