### ISSUE TITLE
Change temporary directory.

### ISSUE THREAD

**Issue by GeekBoy3347** [tslocum/TinyIB#24]
Is there a way of doing this?

**Comment by Wqer555** [comment]
We need more details. What are you trying to do and why?

**Comment by GeekBoy3347** [comment]
I'm trying to post a test picture on the board and it's giving me the error "Missing a temporary folder."
I'm using a online web host to host the board.

**Comment by Wqer555** [comment]
When PHP receives a file, it's stored in the system's default tmp directory until it is moved with [move_uploaded_file](https://secure.php.net/manual/en/function.move-uploaded-file.php). You can try changing the value of [upload_tmp_dir](https://secure.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) in php.ini. Of course, that's if your web host allows it.
