### ISSUE TITLE
"Supported file types are GIF, JPG, PNG, SWF and WebM" when uploading WebM

### ISSUE THREAD

**Issue by Soleedus** [tslocum/TinyIB#25]
WebM support is set to "true" in settings.php, and both mediainfo and ffmpegthumbnailer are installed/functional. TinyIB rejects WebM posts for some reason, and provides the above error message.

**Comment by tslocum** [comment]
Could you please upload the WebM file you tested?  This error is displayed when the MIME type was unmatched, meaning the file isn't being read as video/webm or audio/webm.

**Comment by ferngarc** [comment]
Any chance in the future to add the feature of clicking an image to enlarge
it, instead of it directing you to a direct image page?

**Comment by tslocum** [comment]
@ferngarc Sure, I've meant to add such a feature for some time.  I've committed the necessary changes.

**Comment by Soleedus** [comment]
I've tried a lot of WebMs, it's not file-specific.

**Comment by tslocum** [comment]
Could you please paste the TINYIB_WEBM line from your settings.php?

**Comment by Soleedus** [comment]
define('TINYIB_WEBM', true);

It says WebM is an accepted filetype -- when I go to post with a WebM,
however, it rejects the post on the basis on an invalid filetype.

**Comment by tslocum** [comment]
Below [this line](https://github.com/tslocum/TinyIB/blob/eedef06bbfc965581e4891078272b9cf12c481cc/imgboard.php#L192) add `echo $file_mime_output;`, the output might give a clue.

**Comment by Soleedus** [comment]
Did that and, interestingly, nothing is echoed when attempting to upload a webm.

**Comment by tslocum** [comment]
Change the line you added to `echo 'file --mime-type ' . $file_location;die();` Then try running that command as the user which runs PHP (usually www-data in my experience) from the directory containing imgboard.php, it seems like your PHP user might not be able/allowed to reach the `file` binary.

**Comment by tslocum** [comment]
Any luck @Soleedus?

**Comment by Soleedus** [comment]
Hey, here's the echo:
`file --mime-type src/1475288262050.webm`

**Comment by Soleedus** [comment]
The webm is being uploaded to the /src/ directory, but it doesn't appear in the board index, or anywhere else for that matter.

**Comment by tslocum** [comment]
Try running that command from the directory containing imgboard.php, does it return a MIME type?

**Comment by Soleedus** [comment]
Yeah, there's definitely something up with my permissions. Not something wrong with your software.
