### ISSUE TITLE
Error displaying simple captcha

### ISSUE THREAD

**Issue by loskiq** [tslocum/TinyIB#27]
![screenshot-6oct2016-23 36 27](https://cloud.githubusercontent.com/assets/22175047/19169583/c82d6234-8c1d-11e6-9656-45da6b53732f.png)

What to do?

**Comment by tslocum** [comment]
Seems like the font isn't being loaded properly or there is some issue with GD.  Do you have access to PHP's error log?  It might explain what the issue is.  Just in case it is the font, ensure that PHP has permission to read the files in inc/fonts/

**Comment by loskiq** [comment]
@tslocum log:

\nWarning: No such file or directory in /var/www/b/inc/captcha.php on line 314
\nWarning: Invalid font filename roboto_regular.ttf in /var/www/b/inc/captcha.php on line 314
\nWarning: No such file or directory in /var/www/b/inc/captcha.php on line 318
\nWarning: Invalid font filename roboto_regular.ttf in /var/www/b/inc/captcha.php on line 318

**Comment by tslocum** [comment]
Try changing [this line](https://github.com/tslocum/TinyIB/blob/master/inc/captcha.php#L13) to `putenv('GDFONTPATH=' . realpath(dirname(__FILE__)) . '/fonts/');`

**Comment by loskiq** [comment]
Did not help. I installed php on hhvm. Maybe that's the problem?

**Comment by tslocum** [comment]
Above that line add `echo  realpath(dirname(__FILE__)) . '/fonts/';die();`

If the path is correct your permissions must be at fault.

**Comment by loskiq** [comment]
/var/www/b/inc/fonts/

The path to the correct folder.

/var/www/b/inc/fonts/roboto_bold.ttf
/var/www/b/inc/fonts/roboto_regular.ttf

There are fonts

**Comment by tslocum** [comment]
Thanks for checking.  Since the correct font path is used the only explanation which comes to my mind is that PHP doesn't have permission to read these files.
