### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' in /var/www/htdocs/inc/functions.php on line 239

### ISSUE THREAD

**Issue by owk444** [tslocum/TinyIB#29]
Hello.

I got this error on the first start. Installation does not works. How it can be fixed?

An error line is:
if (count($resp->getErrorCodes()) == 1 && $resp->getErrorCodes()[0] == 'missing-input-response') {

PHP 5.3.3 (cli) (built: Feb  9 2016 10:21:34) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

# php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mcrypt
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
zip
zlib

[Zend Modules]

Thank you

**Comment by Wqer555** [comment]
Post the full error.
Also, upgrade your PHP.  5.3.3 came out 22 July 2010.
