### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by ventolinmono** [tslocum/TinyIB#31]
Very nice imageboard!

Having trouble with embed. Getting this:

> Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/sitio/public_html/inc/functions.php:534 Stack trace: #0 /var/www/sitio/public_html/imgboard.php(103): getEmbed('https://youtu.b...') #1 {main} thrown in /var/www/sitio/public_html/inc/functions.php on line 534

Curl installed with PHP 7.

**Comment by tslocum** [comment]
Have you opened a support ticket with your host?  This seems like an issue with your PHP installation as I run PHP7 as well and curl_init is present and working properly.
