### ISSUE TITLE
Parse error?

### ISSUE THREAD

**Issue by decoratedbug** [tslocum/TinyIB#32]
```Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /var/www/html/board/settings.php on line 39```
I enabled the other three file types in settings.php but when I test it by uploading a webm it gives me that error. I have done this too `sudo apt-get install mediainfo ffmpegthumbnailer`

**Comment by Wqer555** [comment]
The error tells you what the problem is. You need to properly format the code. Post it here if you need help.

**Comment by tslocum** [comment]
Please share the relevant part of your settings.php if you are still encountering this issue.
