### ISSUE TITLE
Return to main thread instead of index

### ISSUE THREAD

**Issue by indrakaw** [tslocum/TinyIB#33]
Current: Whenever I made a thread or replied to OP, it returns to board index.
Expected: Return to main thread.

Please?

**Comment by Wqer555** [comment]
Put "noko" in the email field.

https://github.com/tslocum/TinyIB/blob/master/imgboard.php#L285

**Comment by indrakaw** [comment]
@Wqer555 
Wow, that's undocumented!
I hope that could be an option that can easy defined on `settings.php`.

**Comment by Wqer555** [comment]
It's a staple of imageboards. If you want, you can remove that `if` entirely. That way, the behavior will happen all the time. Alternatively, you can add a variable to `settings.php` and check whether it's true in that same `if`.
