### ISSUE TITLE
Error when uploading media to site running TinyIB

### ISSUE THREAD

**Issue by gamizard** [tslocum/TinyIB#34]
When trying to upload a swf, png, or jpg file, it just told me "Supported file types are JPG, PNG, GIF and SWF." I need help.

**Comment by Alionides** [comment]
how did you solve this problem?

**Comment by tslocum** [comment]
Did you mean to reopen this @braydenk0916?  If so, please paste your `$tinyib_uploads` from settings.php

**Comment by braydenk0916** [comment]
$tinyib_uploads = array('image/jpeg'                    => array('jpg'),
                        'image/pjpeg'                   => array('jpg'),
                        'image/png'                     => array('png'),
                        'image/gif'                     => array('gif'),
                        'application/x-shockwave-flash' => array('swf', 'swf_thumbnail.png'));
                      # 'video/webm'                    => array('webm')); // WebM upload requires mediainfo and ffmpegthumbnailer  (see README for instructions)
                     # 'audio/webm'                    => array('webm'));

**Comment by gamizard** [comment]
Does anyone know how to fix this?

**Comment by Wqer555** [comment]
https://github.com/tslocum/TinyIB/issues/25
https://github.com/tslocum/TinyIB/issues/28

There's been 2 issues on this.
