### ISSUE TITLE
connecting to mysql database on 000webhost?

### ISSUE THREAD

**Issue by vchanadmin** [tslocum/TinyIB#36]
I have very little experience with databases, can someone help me out w/ using mysql on 000webhost? I created a database on 000webhost but it still says "Mysql library is not installled". Thanks

**Comment by tslocum** [comment]
Hey @vchanadmin, are you using the "mysql" or the "mysqli" DBMODE?  Please try using the alternative and you might have more luck.

**Comment by vchanadmin** [comment]
@tslocum that fixed it it seems. However now it says "Could not connect to database: ProxySQL Error: Access denied". I'm sorry for all the questions i have little experience

**Comment by tslocum** [comment]
No problem.  You'll need to enter the MySQL database which you created as DBNAME, as well as provide a username and password for an account with access to that database as DBUSERNAME and DBPASSWORD.  Your host should be able to provide this info.

**Comment by vchanadmin** [comment]
thanks i got it
