### ISSUE TITLE
Chmod problem

### ISSUE THREAD

**Issue by snow-frog** [tslocum/TinyIB#37]
No matter what permissions are given; it always gives:
"Directory 'res' can not be written to. Please modify its permissions."
Either bug or installation instructions just need to be more explicit because you can do a billion things with chmod, 999.999.999 of them being the wrong one.

**Comment by tslocum** [comment]
Please try CHMOD'ing to 777 temporarily to see if you still encounter the issue, if so there might be something which needs to be tweaked regarding your host's PHP and/or web server configuration.  TinyIB uses `is_writable()` so I don't believe it's a bug.
