### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by AirForce11** [tslocum/TinyIB#48]
is there any way to set the timezone? i looked at the server config and ib code and cant seem to get the time zone set to eastern time so when one posts the time zone shows in eastern time

**Comment by tslocum** [comment]
A timezone option would be nice to have and fairly easy to add, I will add it in fairly soon.

**Comment by AirForce11** [comment]
Thank you.  I could not figure out how to change the time zone to eastern time. Like, even when everyone posts if it showed they posted on eastern time that would be fine. I figured there may be an easy fix since it is allready set to some other time.
Tiny ib is amazing code, it never fails on any version of php.

**Comment by tslocum** [comment]
Thanks for the kind words.  For eastern time add to settings.php:

```php
define('TINYIB_TIMEZONE', 'America/New_York');
```

**Comment by tslocum** [comment]
Note that TINYIB_TIMEZONE only affects new posts as the date portion of the post data is stored in a rendered state.

**Comment by AirForce11** [comment]
Worked, thank you so much.

**Comment by AirForce11** [comment]
is mysql required for it to work? I added it in flatfile mode to settings.php and time is still wrong

**Comment by AirForce11** [comment]
Also are you avail for a consultation? I need help with a serious project. either phone, text or email... i will pay you to answer some questions. seriously.
