### ISSUE TITLE
Cannot unstick posts using SQL

### ISSUE THREAD

**Issue by pitamatein** [tslocum/TinyIB#49]
Used sqlite3 and was unable to "unstick" a post. Back end toggled the stick/unstick text and icon, but the post would still remain at the top after subsequent post.

Things work correctly when using flatfile.

**Comment by tslocum** [comment]
I will look into this in the next few days.

**Comment by tslocum** [comment]
To resolve this a query must be executed once on your SQLite database.  Note that this will cause all threads to be reset to an un-stickied state.

Above the following lines in inc/database_sqlite.php or inc/database_sqlite3.php (depending on your DBMODE):

```php
// Add stickied column if it isn't present
@$db->exec("ALTER TABLE " . TINYIB_DBPOSTS . " ADD COLUMN stickied INTEGER NOT NULL DEFAULT '0'");
```

Add:

```php
@$db->exec("ALTER TABLE " . TINYIB_DBPOSTS . " DROP COLUMN stickied");
```

(If you're using the old sqlite DBmode, this line will be slightly different.  But you should really just take this opportunity to upgrade to sqlite3)

Once the line has been added, open any page in the management panel, then delete the new line.  Newly un-stickied threads will now behave properly.
